In [45]:
import pandas as pd

In [46]:
match_data = pd.read_csv("../data/match_data.csv")
match_info_data = pd.read_csv("../data/match_info_data.csv")

C:\Users\Nithish\AppData\Local\Temp\ipykernel_25192\2981192924.py:1: DtypeWarning: Columns (0: season) have mixed types. Specify dtype option on import or set low_memory=False.
  match_data = pd.read_csv("../data/match_data.csv")

In [47]:
match_data.head()

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed,cricsheet_id
0,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.1,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353
1,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.2,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353
2,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.3,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353
3,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.4,Gujarat Titans,Chennai Super Kings,Shubman Gill,WP Saha,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353
4,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.5,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370353

In [48]:
match_data.shape

(243817, 23)

In [49]:
match_info_data.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1370353,2023,Ahmedabad,2023/05/29,Gujarat Titans,Chennai Super Kings,Chennai Super Kings,field,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
1,1370352,2023,Ahmedabad,2023/05/26,Gujarat Titans,Mumbai Indians,Mumbai Indians,field,normal,0,Gujarat Titans,62,0,Shubman Gill,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,J Madanagopal
2,1370351,2023,Chennai,2023/05/24,Mumbai Indians,Lucknow Super Giants,Mumbai Indians,bat,normal,0,Mumbai Indians,81,0,Akash Madhwal,"MA Chidambaram Stadium, Chepauk, Chennai",BNJ Oxenford,VK Sharma,CB Gaffaney
3,1370350,2023,Chennai,2023/05/23,Chennai Super Kings,Gujarat Titans,Gujarat Titans,field,normal,0,Chennai Super Kings,15,0,RD Gaikwad,"MA Chidambaram Stadium, Chepauk, Chennai",AK Chaudhary,CB Gaffaney,BNJ Oxenford
4,1359543,2023,Mumbai,2023/05/21,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,8,C Green,"Wankhede Stadium, Mumbai",KN Ananthapadmanabhan,RJ Tucker,R Pandit

In [50]:
match_info_data.shape

(1024, 18)

In [51]:
match_data.columns

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed', 'cricsheet_id'],
      dtype='str')

In [52]:
match_info_data.columns

Index(['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='str')

In [53]:
match_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 243817 entries, 0 to 243816
Data columns (total 23 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   match_id                243817 non-null  int64
 1   season                  243817 non-null  object
 2   start_date              243817 non-null  str
 3   venue                   243817 non-null  str
 4   innings                 243817 non-null  int64
 5   ball                    243817 non-null  float64
 6   batting_team            243817 non-null  str
 7   bowling_team            243817 non-null  str
 8   striker                 243817 non-null  str
 9   non_striker             243817 non-null  str
 10  bowler                  243817 non-null  str
 11  runs_off_bat            243817 non-null  int64
 12  extras                  243817 non-null  int64
 13  wides                   7652 non-null    float64
 14  noballs                 1018 non-null    float64
 15  byes                    628 non-null     float64
 16  legbyes                 3778 non-null    float64
 17  penalty                 2 non-null       float64
 18  wicket_type             12067 non-null   str
 19  player_dismissed        12067 non-null   str
 20  other_wicket_type       0 non-null       float64
 21  other_player_dismissed  0 non-null       float64
 22  cricsheet_id            243817 non-null  int64
dtypes: float64(8), int64(5), object(1), str(9)
memory usage: 42.8+ MB

In [54]:
match_info_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1024 entries, 0 to 1023
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1024 non-null   int64
 1   season           1024 non-null   str
 2   city             973 non-null    str
 3   date             1024 non-null   str
 4   team1            1024 non-null   str
 5   team2            1024 non-null   str
 6   toss_winner      1024 non-null   str
 7   toss_decision    1024 non-null   str
 8   result           1024 non-null   str
 9   dl_applied       1024 non-null   int64
 10  winner           1005 non-null   str
 11  win_by_runs      1024 non-null   int64
 12  win_by_wickets   1024 non-null   int64
 13  player_of_match  1019 non-null   str
 14  venue            1024 non-null   str
 15  umpire1          1024 non-null   str
 16  umpire2          1024 non-null   str
 17  umpire3          1021 non-null   str
dtypes: int64(4), str(14)
memory usage: 144.1 KB

In [55]:
match_info_data.duplicated().sum()

0

In [56]:
match_data.duplicated().sum()

2

In [57]:
match_data = match_data.drop_duplicates()

In [58]:
match_data.duplicated().sum()

0

In [59]:
match_data.isnull().sum()

match_id                       0
season                         0
start_date                     0
venue                          0
innings                        0
ball                           0
batting_team                   0
bowling_team                   0
striker                        0
non_striker                    0
bowler                         0
runs_off_bat                   0
extras                         0
wides                     236163
noballs                   242797
byes                      243187
legbyes                   240037
penalty                   243813
wicket_type               231748
player_dismissed          231748
other_wicket_type         243815
other_player_dismissed    243815
cricsheet_id                   0
dtype: int64

In [60]:
match_info_data.isnull().sum()

id                  0
season              0
city               51
date                0
team1               0
team2               0
toss_winner         0
toss_decision       0
result              0
dl_applied          0
winner             19
win_by_runs         0
win_by_wickets      0
player_of_match     5
venue               0
umpire1             0
umpire2             0
umpire3             3
dtype: int64

In [61]:
match_info_data = match_info_data.dropna(subset=['winner'])

In [62]:
match_info_data['winner'].isnull().sum()

0

In [63]:
match_data[['runs_off_bat', 'extras']].head(15)

    runs_off_bat  extras
0              0       0
1              0       0
2              1       0
3              1       0
4              1       0
5              1       0
6              0       0
7              1       0
8              1       0
9              1       0
10             0       0
11             1       0
12             6       0
13             0       0
14             4       0

In [64]:
merged_data = match_data.merge(
    match_info_data,
    left_on='match_id',
    right_on='id'
)

In [65]:
merged_data.head()

,match_id,season_x,start_date,venue_x,innings,ball,batting_team,bowling_team,striker,non_striker,...,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue_y,umpire1,umpire2,umpire3
0,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.1,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
1,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.2,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
2,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.3,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
3,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.4,Gujarat Titans,Chennai Super Kings,Shubman Gill,WP Saha,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan
4,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",1,0.5,Gujarat Titans,Chennai Super Kings,WP Saha,Shubman Gill,...,D/L,1,Chennai Super Kings,0,5,DP Conway,"Narendra Modi Stadium, Ahmedabad",Nitin Menon,RJ Tucker,KN Ananthapadmanabhan

In [66]:
merged_data['total_runs'] = merged_data['runs_off_bat'] + merged_data['extras']

In [67]:
merged_data['current_score'] = merged_data.groupby(
    ['match_id', 'innings']
)['total_runs'].cumsum()

In [68]:
merged_data[
    ['match_id','innings','ball','total_runs','current_score']
].head(20)

    match_id  innings  ball  total_runs  current_score
0    1370353        1   0.1           0              0
1    1370353        1   0.2           0              0
2    1370353        1   0.3           1              1
3    1370353        1   0.4           1              2
4    1370353        1   0.5           1              3
5    1370353        1   0.6           1              4
6    1370353        1   1.1           0              4
7    1370353        1   1.2           1              5
8    1370353        1   1.3           1              6
9    1370353        1   1.4           1              7
10   1370353        1   1.5           0              7
11   1370353        1   1.6           1              8
12   1370353        1   2.1           6             14
13   1370353        1   2.2           0             14
14   1370353        1   2.3           4             18
15   1370353        1   2.4           4             22
16   1370353        1   2.5           2             24
17   1370353        1   2.6           0             24
18   1370353        1   3.1           4             28
19   1370353        1   3.2           4             32

In [69]:
merged_data['is_wicket'] = merged_data['player_dismissed'].notna().astype(int)

In [70]:
merged_data['wickets_lost'] = merged_data.groupby(
    ['match_id', 'innings']
)['is_wicket'].cumsum()

In [71]:
merged_data[
    ['ball', 'player_dismissed', 'is_wicket', 'wickets_lost']
].head(20)

    ball player_dismissed  is_wicket  wickets_lost
0    0.1              NaN          0             0
1    0.2              NaN          0             0
2    0.3              NaN          0             0
3    0.4              NaN          0             0
4    0.5              NaN          0             0
5    0.6              NaN          0             0
6    1.1              NaN          0             0
7    1.2              NaN          0             0
8    1.3              NaN          0             0
9    1.4              NaN          0             0
10   1.5              NaN          0             0
11   1.6              NaN          0             0
12   2.1              NaN          0             0
13   2.2              NaN          0             0
14   2.3              NaN          0             0
15   2.4              NaN          0             0
16   2.5              NaN          0             0
17   2.6              NaN          0             0
18   3.1              NaN          0             0
19   3.2              NaN          0             0

In [72]:
merged_data['balls_bowled'] = merged_data.groupby(
    ['match_id', 'innings']
).cumcount() + 1

In [73]:
merged_data[
    ['ball', 'balls_bowled']
].head(20)

    ball  balls_bowled
0    0.1             1
1    0.2             2
2    0.3             3
3    0.4             4
4    0.5             5
5    0.6             6
6    1.1             7
7    1.2             8
8    1.3             9
9    1.4            10
10   1.5            11
11   1.6            12
12   2.1            13
13   2.2            14
14   2.3            15
15   2.4            16
16   2.5            17
17   2.6            18
18   3.1            19
19   3.2            20

In [74]:
merged_data['overs_completed'] = merged_data['balls_bowled'] / 6

In [75]:
merged_data[
    ['ball', 'balls_bowled', 'overs_completed']
].head(15)

    ball  balls_bowled  overs_completed
0    0.1             1         0.166667
1    0.2             2         0.333333
2    0.3             3         0.500000
3    0.4             4         0.666667
4    0.5             5         0.833333
5    0.6             6         1.000000
6    1.1             7         1.166667
7    1.2             8         1.333333
8    1.3             9         1.500000
9    1.4            10         1.666667
10   1.5            11         1.833333
11   1.6            12         2.000000
12   2.1            13         2.166667
13   2.2            14         2.333333
14   2.3            15         2.500000

In [76]:
merged_data['current_run_rate'] = (
    merged_data['current_score'] / merged_data['overs_completed']
)

In [77]:
merged_data[
    ['current_score', 'overs_completed', 'current_run_rate']
].head(15)

    current_score  overs_completed  current_run_rate
0               0         0.166667          0.000000
1               0         0.333333          0.000000
2               1         0.500000          2.000000
3               2         0.666667          3.000000
4               3         0.833333          3.600000
5               4         1.000000          4.000000
6               4         1.166667          3.428571
7               5         1.333333          3.750000
8               6         1.500000          4.000000
9               7         1.666667          4.200000
10              7         1.833333          3.818182
11              8         2.000000          4.000000
12             14         2.166667          6.461538
13             14         2.333333          6.000000
14             18         2.500000          7.200000

In [78]:
merged_data['final_score'] = merged_data.groupby(
    ['match_id', 'innings']
)['current_score'].transform('max')

In [79]:
merged_data[
    ['match_id', 'innings', 'current_score', 'final_score']
].tail(20)

        match_id  innings  current_score  final_score
239671    335982        2             68           82
239672    335982        2             69           82
239673    335982        2             69           82
239674    335982        2             69           82
239675    335982        2             70           82
239676    335982        2             70           82
239677    335982        2             71           82
239678    335982        2             71           82
239679    335982        2             71           82
239680    335982        2             71           82
239681    335982        2             77           82
239682    335982        2             78           82
239683    335982        2             78           82
239684    335982        2             78           82
239685    335982        2             79           82
239686    335982        2             80           82
239687    335982        2             81           82
239688    335982        2             81           82
239689    335982        2             82           82
239690    335982        2             82           82

In [80]:
projected_score_data = merged_data[
    merged_data['ball'].astype(str).str.endswith('.6')
].copy()

In [81]:
projected_score_data[
    ['match_id', 'innings', 'ball', 'current_score', 'final_score']
].head(20)

     match_id  innings  ball  current_score  final_score
5     1370353        1   0.6              4          214
11    1370353        1   1.6              8          214
17    1370353        1   2.6             24          214
23    1370353        1   3.6             38          214
29    1370353        1   4.6             49          214
35    1370353        1   5.6             62          214
41    1370353        1   6.6             67          214
47    1370353        1   7.6             72          214
53    1370353        1   8.6             80          214
59    1370353        1   9.6             86          214
65    1370353        1  10.6             96          214
71    1370353        1  11.6            108          214
79    1370353        1  12.6            124          214
85    1370353        1  13.6            131          214
91    1370353        1  14.6            143          214
97    1370353        1  15.6            153          214
103   1370353        1  16.6            173          214
109   1370353        1  17.6            182          214
115   1370353        1  18.6            200          214
121   1370353        1  19.6            214          214

In [82]:
projected_score_data = projected_score_data[
    [
        'batting_team',
        'bowling_team',
        'venue_x',
        'current_score',
        'wickets_lost',
        'overs_completed',
        'current_run_rate',
        'final_score'
    ]
]

In [83]:
projected_score_data.head()

,batting_team,bowling_team,venue_x,current_score,wickets_lost,overs_completed,current_run_rate,final_score
5,Gujarat Titans,Chennai Super Kings,"Narendra Modi Stadium, Ahmedabad",4,0,1.0,4.0,214
11,Gujarat Titans,Chennai Super Kings,"Narendra Modi Stadium, Ahmedabad",8,0,2.0,4.0,214
17,Gujarat Titans,Chennai Super Kings,"Narendra Modi Stadium, Ahmedabad",24,0,3.0,8.0,214
23,Gujarat Titans,Chennai Super Kings,"Narendra Modi Stadium, Ahmedabad",38,0,4.0,9.5,214
29,Gujarat Titans,Chennai Super Kings,"Narendra Modi Stadium, Ahmedabad",49,0,5.0,9.8,214

In [84]:
X = projected_score_data.drop('final_score', axis=1)
y = projected_score_data['final_score']

In [85]:
X.head()

,batting_team,bowling_team,venue_x,current_score,wickets_lost,overs_completed,current_run_rate
5,Gujarat Titans,Chennai Super Kings,"Narendra Modi Stadium, Ahmedabad",4,0,1.0,4.0
11,Gujarat Titans,Chennai Super Kings,"Narendra Modi Stadium, Ahmedabad",8,0,2.0,4.0
17,Gujarat Titans,Chennai Super Kings,"Narendra Modi Stadium, Ahmedabad",24,0,3.0,8.0
23,Gujarat Titans,Chennai Super Kings,"Narendra Modi Stadium, Ahmedabad",38,0,4.0,9.5
29,Gujarat Titans,Chennai Super Kings,"Narendra Modi Stadium, Ahmedabad",49,0,5.0,9.8

In [86]:
y.head()

5     214
11    214
17    214
23    214
29    214
Name: final_score, dtype: int64

In [87]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [88]:
RandomForestRegressor().fit(X_train, y_train)

NameError: name 'RandomForestRegressor' is not defined

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            'cat',
            OneHotEncoder(handle_unknown='ignore'),
            ['batting_team', 'bowling_team', 'venue_x']
        )
    ],
    remainder='passthrough'
)

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor(
        n_estimators=100,
        random_state=42
    ))
])

In [ ]:
model.fit(X_train, y_train)

c:\Users\Nithish\anaconda3\Lib\site-packages\sklearn\compose\_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['batting_team',
                                                   'bowling_team',
                                                   'venue_x'])])),
                ('regressor', RandomForestRegressor(random_state=42))])

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import mean_absolute_error, r2_score

In [ ]:
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error:", mae)
print("R² Score:", r2)

Mean Absolute Error: 13.85968609524639
R² Score: 0.5831560396225097

In [ ]:
projected_score_data = projected_score_data[
    projected_score_data['innings'] == 1
]

KeyError: 'innings'

In [ ]:
projected_score_data = projected_score_data[
    [
        'batting_team',
        'bowling_team',
        'venue_x',
        'current_score',
        'wickets_lost',
        'overs_completed',
        'current_run_rate',
        'final_score'
    ]
]

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import mean_absolute_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("R2:", r2)

MAE: 13.85968609524639
R2: 0.5831560396225097

In [ ]:
import joblib

joblib.dump(model, "../model/projected_score_model.pkl")

['../model/projected_score_model.pkl']

In [ ]:
import os

os.listdir("../model")

['projected_score_model.pkl']

In [ ]:
win_data = merged_data[merged_data['innings'] == 2].copy()

In [ ]:
win_data.head()

,match_id,season_x,start_date,venue_x,innings,ball,batting_team,bowling_team,striker,non_striker,...,umpire2,umpire3,total_runs,current_score,is_wicket,wickets_lost,balls_bowled,overs_completed,current_run_rate,final_score
122,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,0.1,Chennai Super Kings,Gujarat Titans,RD Gaikwad,DP Conway,...,RJ Tucker,KN Ananthapadmanabhan,0,0,0,0,1,0.166667,0.0,171
123,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,0.2,Chennai Super Kings,Gujarat Titans,RD Gaikwad,DP Conway,...,RJ Tucker,KN Ananthapadmanabhan,0,0,0,0,2,0.333333,0.0,171
124,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,0.3,Chennai Super Kings,Gujarat Titans,RD Gaikwad,DP Conway,...,RJ Tucker,KN Ananthapadmanabhan,4,4,0,0,3,0.500000,8.0,171
125,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,0.4,Chennai Super Kings,Gujarat Titans,RD Gaikwad,DP Conway,...,RJ Tucker,KN Ananthapadmanabhan,2,6,0,0,4,0.666667,9.0,171
126,1370353,2023,2023-05-29,"Narendra Modi Stadium, Ahmedabad",2,0.5,Chennai Super Kings,Gujarat Titans,RD Gaikwad,DP Conway,...,RJ Tucker,KN Ananthapadmanabhan,0,6,0,0,5,0.833333,7.2,171

In [ ]:
first_innings = merged_data[merged_data['innings'] == 1].groupby('match_id')['final_score'].max()

win_data['target'] = win_data['match_id'].map(first_innings) + 1

In [ ]:
win_data[['match_id','current_score','target']].head()

     match_id  current_score  target
122   1370353              0     215
123   1370353              0     215
124   1370353              4     215
125   1370353              6     215
126   1370353              6     215

In [90]:
win_data['runs_left'] = win_data['target'] - win_data['current_score']

NameError: name 'win_data' is not defined

In [ ]:
win_data[['current_score','target','runs_left']].head()

     current_score  target  runs_left
122              0     215        215
123              0     215        215
124              4     215        211
125              6     215        209
126              6     215        209

In [ ]:
win_data['balls_left'] = 120 - win_data['balls_bowled']

In [ ]:
win_data[['balls_bowled','balls_left']].head()

     balls_bowled  balls_left
122             1         119
123             2         118
124             3         117
125             4         116
126             5         115

In [ ]:
win_data['wickets_left'] = 10 - win_data['wickets_lost']

In [91]:
win_data[['wickets_lost','wickets_left']].head()

NameError: name 'win_data' is not defined

In [ ]:
win_data['required_run_rate'] = (
    win_data['runs_left'] * 6
) / win_data['balls_left']

In [ ]:
win_data[
    ['runs_left','balls_left','required_run_rate']
].head()

     runs_left  balls_left  required_run_rate
122        215         119          10.840336
123        215         118          10.932203
124        211         117          10.820513
125        209         116          10.810345
126        209         115          10.904348

In [ ]:
win_data['batting_team_won'] = (
    win_data['batting_team'] == win_data['winner']
).astype(int)

In [ ]:
win_data[
    ['batting_team','winner','batting_team_won']
].head()

            batting_team               winner  batting_team_won
122  Chennai Super Kings  Chennai Super Kings                 1
123  Chennai Super Kings  Chennai Super Kings                 1
124  Chennai Super Kings  Chennai Super Kings                 1
125  Chennai Super Kings  Chennai Super Kings                 1
126  Chennai Super Kings  Chennai Super Kings                 1

In [ ]:
win_model_data = win_data[
    [
        'batting_team',
        'bowling_team',
        'venue_x',
        'current_score',
        'runs_left',
        'balls_left',
        'wickets_left',
        'current_run_rate',
        'required_run_rate',
        'batting_team_won'
    ]
]

In [ ]:
win_model_data.head()

,batting_team,bowling_team,venue_x,current_score,runs_left,balls_left,wickets_left,current_run_rate,required_run_rate,batting_team_won
122,Chennai Super Kings,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",0,215,119,10,0.0,10.840336,1
123,Chennai Super Kings,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",0,215,118,10,0.0,10.932203,1
124,Chennai Super Kings,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",4,211,117,10,8.0,10.820513,1
125,Chennai Super Kings,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",6,209,116,10,9.0,10.810345,1
126,Chennai Super Kings,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",6,209,115,10,7.2,10.904348,1

In [ ]:
X = win_model_data.drop('batting_team_won', axis=1)
y = win_model_data['batting_team_won']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

preprocessor = ColumnTransformer(
    transformers=[
        (
            'cat',
            OneHotEncoder(handle_unknown='ignore'),
            ['batting_team', 'bowling_team', 'venue_x']
        )
    ],
    remainder='passthrough'
)

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

win_model = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(max_iter=1000))
])

In [ ]:
win_model.fit(X_train, y_train)

c:\Users\Nithish\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
win_model_data.isnull().sum()

batting_team         0
bowling_team         0
venue_x              0
current_score        0
runs_left            0
balls_left           0
wickets_left         0
current_run_rate     0
required_run_rate    8
batting_team_won     0
dtype: int64

In [ ]:
win_model_data = win_model_data.dropna()

In [ ]:
win_model_data.isnull().sum()

batting_team         0
bowling_team         0
venue_x              0
current_score        0
runs_left            0
balls_left           0
wickets_left         0
current_run_rate     0
required_run_rate    0
batting_team_won     0
dtype: int64

In [ ]:
X = win_model_data.drop('batting_team_won', axis=1)
y = win_model_data['batting_team_won']

In [ ]:
win_model.fit(X_train, y_train)

c:\Users\Nithish\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
X.isnull().sum()

batting_team         0
bowling_team         0
venue_x              0
current_score        0
runs_left            0
balls_left           0
wickets_left         0
current_run_rate     0
required_run_rate    0
dtype: int64

In [ ]:
import numpy as np

X.isin([np.inf, -np.inf]).sum()

batting_team           0
bowling_team           0
venue_x                0
current_score          0
runs_left              0
balls_left             0
wickets_left           0
current_run_rate       0
required_run_rate    559
dtype: int64

In [ ]:
import numpy as np

X[
    X.isnull().any(axis=1) |
    X.isin([np.inf, -np.inf]).any(axis=1)
]

,batting_team,bowling_team,venue_x,current_score,runs_left,balls_left,wickets_left,current_run_rate,required_run_rate
927,Gujarat Titans,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk, Chennai",142,31,0,2,7.10,inf
1423,Gujarat Titans,Royal Challengers Bangalore,"M Chinnaswamy Stadium, Bengaluru",190,8,0,6,9.50,inf
1675,Delhi Capitals,Chennai Super Kings,"Arun Jaitley Stadium, Delhi",145,79,0,3,7.25,inf
1929,Kolkata Knight Riders,Lucknow Super Giants,"Eden Gardens, Kolkata",158,19,0,3,7.90,inf
2180,Rajasthan Royals,Punjab Kings,"Himachal Pradesh Cricket Association Stadium, ...",179,9,0,5,8.95,inf
...,...,...,...,...,...,...,...,...,...
237809,Rajasthan Royals,Deccan Chargers,"Rajiv Gandhi International Stadium, Uppal",205,10,0,3,10.25,inf
238058,Mumbai Indians,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk",189,20,0,3,9.45,inf
238755,Royal Challengers Bangalore,Mumbai Indians,Wankhede Stadium,165,1,0,5,8.25,inf
238996,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,106,5,0,5,5.30,inf
239242,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",200,41,0,6,10.00,inf

In [ ]:
win_model_data = win_model_data[win_model_data['balls_left'] > 0]

In [ ]:
X = win_model_data.drop('batting_team_won', axis=1)
y = win_model_data['batting_team_won']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
win_model.fit(X_train, y_train)

c:\Users\Nithish\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Nithish\anaconda3\Lib\site-packages\sklearn\compose\_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['batting_team',
                                                   'bowling_team',
                                                   'venue_x'])])),
                ('classifier', LogisticRegression(max_iter=1000))])

In [ ]:
y_pred = win_model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.815070310427169

In [ ]:
y_pred = win_model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.815070310427169

In [ ]:
import joblib

joblib.dump(win_model, "../model/win_probability_model.pkl")

['../model/win_probability_model.pkl']

In [ ]:
import os

os.listdir("../model")

['projected_score_model.pkl', 'win_probability_model.pkl']

In [ ]:
print(sorted(merged_data['batting_team'].unique()))
print("Total Teams:", len(merged_data['batting_team'].unique()))

['Chennai Super Kings', 'Deccan Chargers', 'Delhi Capitals', 'Delhi Daredevils', 'Gujarat Lions', 'Gujarat Titans', 'Kings XI Punjab', 'Kochi Tuskers Kerala', 'Kolkata Knight Riders', 'Lucknow Super Giants', 'Mumbai Indians', 'Pune Warriors', 'Punjab Kings', 'Rajasthan Royals', 'Rising Pune Supergiant', 'Rising Pune Supergiants', 'Royal Challengers Bangalore', 'Sunrisers Hyderabad']
Total Teams: 18

In [ ]:
print(sorted(merged_data['venue_x'].unique()))
print("Total Venues:", len(merged_data['venue_x'].unique()))

['Arun Jaitley Stadium', 'Arun Jaitley Stadium, Delhi', 'Barabati Stadium', 'Barsapara Cricket Stadium, Guwahati', 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow', 'Brabourne Stadium', 'Brabourne Stadium, Mumbai', 'Buffalo Park', 'De Beers Diamond Oval', 'Dr DY Patil Sports Academy', 'Dr DY Patil Sports Academy, Mumbai', 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium', 'Dubai International Cricket Stadium', 'Eden Gardens', 'Eden Gardens, Kolkata', 'Feroz Shah Kotla', 'Green Park', 'Himachal Pradesh Cricket Association Stadium', 'Himachal Pradesh Cricket Association Stadium, Dharamsala', 'Holkar Cricket Stadium', 'JSCA International Stadium Complex', 'Kingsmead', 'M Chinnaswamy Stadium', 'M Chinnaswamy Stadium, Bengaluru', 'M.Chinnaswamy Stadium', 'MA Chidambaram Stadium', 'MA Chidambaram Stadium, Chepauk', 'MA Chidambaram Stadium, Chepauk, Chennai', 'Maharashtra Cricket Association Stadium', 'Maharashtra Cricket Association Stadium, Pune', 'Narendra Modi Stadium, Ahmedabad', 'Nehru Stadium', 'New Wanderers Stadium', 'Newlands', 'OUTsurance Oval', 'Punjab Cricket Association IS Bindra Stadium', 'Punjab Cricket Association IS Bindra Stadium, Mohali', 'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh', 'Punjab Cricket Association Stadium, Mohali', 'Rajiv Gandhi International Stadium', 'Rajiv Gandhi International Stadium, Uppal', 'Rajiv Gandhi International Stadium, Uppal, Hyderabad', 'Sardar Patel Stadium, Motera', 'Saurashtra Cricket Association Stadium', 'Sawai Mansingh Stadium', 'Sawai Mansingh Stadium, Jaipur', 'Shaheed Veer Narayan Singh International Stadium', 'Sharjah Cricket Stadium', 'Sheikh Zayed Stadium', "St George's Park", 'Subrata Roy Sahara Stadium', 'SuperSport Park', 'Vidarbha Cricket Association Stadium, Jamtha', 'Wankhede Stadium', 'Wankhede Stadium, Mumbai', 'Zayed Cricket Stadium, Abu Dhabi']
Total Venues: 56

In [ ]:
sorted(merged_data['batting_team'].unique())

['Chennai Super Kings',
 'Deccan Chargers',
 'Delhi Capitals',
 'Delhi Daredevils',
 'Gujarat Lions',
 'Gujarat Titans',
 'Kings XI Punjab',
 'Kochi Tuskers Kerala',
 'Kolkata Knight Riders',
 'Lucknow Super Giants',
 'Mumbai Indians',
 'Pune Warriors',
 'Punjab Kings',
 'Rajasthan Royals',
 'Rising Pune Supergiant',
 'Rising Pune Supergiants',
 'Royal Challengers Bangalore',
 'Sunrisers Hyderabad']

In [ ]:
sorted(merged_data['venue_x'].unique())

['Arun Jaitley Stadium',
 'Arun Jaitley Stadium, Delhi',
 'Barabati Stadium',
 'Barsapara Cricket Stadium, Guwahati',
 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow',
 'Brabourne Stadium',
 'Brabourne Stadium, Mumbai',
 'Buffalo Park',
 'De Beers Diamond Oval',
 'Dr DY Patil Sports Academy',
 'Dr DY Patil Sports Academy, Mumbai',
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
 'Dubai International Cricket Stadium',
 'Eden Gardens',
 'Eden Gardens, Kolkata',
 'Feroz Shah Kotla',
 'Green Park',
 'Himachal Pradesh Cricket Association Stadium',
 'Himachal Pradesh Cricket Association Stadium, Dharamsala',
 'Holkar Cricket Stadium',
 'JSCA International Stadium Complex',
 'Kingsmead',
 'M Chinnaswamy Stadium',
 'M Chinnaswamy Stadium, Bengaluru',
 'M.Chinnaswamy Stadium',
 'MA Chidambaram Stadium',
 'MA Chidambaram Stadium, Chepauk',
 'MA Chidambaram Stadium, Chepauk, Chennai',
 'Maharashtra Cricket Association Stadium',
 'Maharashtra Cricket Association Stadium, Pune',
 'Narendra Modi Stadium, Ahmedabad',
 'Nehru Stadium',
 'New Wanderers Stadium',
 'Newlands',
 'OUTsurance Oval',
 'Punjab Cricket Association IS Bindra Stadium',
 'Punjab Cricket Association IS Bindra Stadium, Mohali',
 'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh',
 'Punjab Cricket Association Stadium, Mohali',
 'Rajiv Gandhi International Stadium',
 'Rajiv Gandhi International Stadium, Uppal',
 'Rajiv Gandhi International Stadium, Uppal, Hyderabad',
 'Sardar Patel Stadium, Motera',
 'Saurashtra Cricket Association Stadium',
 'Sawai Mansingh Stadium',
 'Sawai Mansingh Stadium, Jaipur',
 'Shaheed Veer Narayan Singh International Stadium',
 'Sharjah Cricket Stadium',
 'Sheikh Zayed Stadium',
 "St George's Park",
 'Subrata Roy Sahara Stadium',
 'SuperSport Park',
 'Vidarbha Cricket Association Stadium, Jamtha',
 'Wankhede Stadium',
 'Wankhede Stadium, Mumbai',
 'Zayed Cricket Stadium, Abu Dhabi']

In [ ]:
sorted(merged_data['batting_team'].unique())

['Chennai Super Kings',
 'Deccan Chargers',
 'Delhi Capitals',
 'Delhi Daredevils',
 'Gujarat Lions',
 'Gujarat Titans',
 'Kings XI Punjab',
 'Kochi Tuskers Kerala',
 'Kolkata Knight Riders',
 'Lucknow Super Giants',
 'Mumbai Indians',
 'Pune Warriors',
 'Punjab Kings',
 'Rajasthan Royals',
 'Rising Pune Supergiant',
 'Rising Pune Supergiants',
 'Royal Challengers Bangalore',
 'Sunrisers Hyderabad']

In [ ]:
sorted(merged_data['venue_x'].unique())

['Arun Jaitley Stadium',
 'Arun Jaitley Stadium, Delhi',
 'Barabati Stadium',
 'Barsapara Cricket Stadium, Guwahati',
 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow',
 'Brabourne Stadium',
 'Brabourne Stadium, Mumbai',
 'Buffalo Park',
 'De Beers Diamond Oval',
 'Dr DY Patil Sports Academy',
 'Dr DY Patil Sports Academy, Mumbai',
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
 'Dubai International Cricket Stadium',
 'Eden Gardens',
 'Eden Gardens, Kolkata',
 'Feroz Shah Kotla',
 'Green Park',
 'Himachal Pradesh Cricket Association Stadium',
 'Himachal Pradesh Cricket Association Stadium, Dharamsala',
 'Holkar Cricket Stadium',
 'JSCA International Stadium Complex',
 'Kingsmead',
 'M Chinnaswamy Stadium',
 'M Chinnaswamy Stadium, Bengaluru',
 'M.Chinnaswamy Stadium',
 'MA Chidambaram Stadium',
 'MA Chidambaram Stadium, Chepauk',
 'MA Chidambaram Stadium, Chepauk, Chennai',
 'Maharashtra Cricket Association Stadium',
 'Maharashtra Cricket Association Stadium, Pune',
 'Narendra Modi Stadium, Ahmedabad',
 'Nehru Stadium',
 'New Wanderers Stadium',
 'Newlands',
 'OUTsurance Oval',
 'Punjab Cricket Association IS Bindra Stadium',
 'Punjab Cricket Association IS Bindra Stadium, Mohali',
 'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh',
 'Punjab Cricket Association Stadium, Mohali',
 'Rajiv Gandhi International Stadium',
 'Rajiv Gandhi International Stadium, Uppal',
 'Rajiv Gandhi International Stadium, Uppal, Hyderabad',
 'Sardar Patel Stadium, Motera',
 'Saurashtra Cricket Association Stadium',
 'Sawai Mansingh Stadium',
 'Sawai Mansingh Stadium, Jaipur',
 'Shaheed Veer Narayan Singh International Stadium',
 'Sharjah Cricket Stadium',
 'Sheikh Zayed Stadium',
 "St George's Park",
 'Subrata Roy Sahara Stadium',
 'SuperSport Park',
 'Vidarbha Cricket Association Stadium, Jamtha',
 'Wankhede Stadium',
 'Wankhede Stadium, Mumbai',
 'Zayed Cricket Stadium, Abu Dhabi']

In [ ]:
projected_score_data[['current_score', 'final_score']].describe()

       current_score   final_score
count   38267.000000  38267.000000
mean       77.824313    158.987822
std        48.525042     30.071247
min         0.000000     44.000000
25%        38.000000    139.000000
50%        74.000000    160.000000
75%       113.000000    179.000000
max       263.000000    263.000000

In [ ]:
(projected_score_data['current_score'] > projected_score_data['final_score']).sum()

0

In [ ]:
import joblib

model = joblib.load("../model/projected_score_model.pkl")

In [ ]:
print(model.named_steps["preprocessor"].feature_names_in_)

['batting_team' 'bowling_team' 'venue_x' 'current_score' 'wickets_lost'
 'overs_completed' 'current_run_rate']

In [ ]:
import pandas as pd

input_df = pd.DataFrame({
    "batting_team": ["Chennai Super Kings"],
    "bowling_team": ["Deccan Chargers"],   # Use the exact bowling team from your Flask test
    "venue_x": ["Arun Jaitley Stadium"],
    "current_score": [234],
    "wickets_lost": [4],
    "overs_completed": [15.0],
    "current_run_rate": [15.6]
})

In [ ]:
prediction = model.predict(input_df)
print(prediction)

[231.16]

In [ ]:
projected_score_data['innings'].value_counts()

KeyError: 'innings'

In [ ]:
merged_data['innings'].value_counts()

innings
1    123925
2    115766
Name: count, dtype: int64

In [ ]:
projected_score_data['innings'].value_counts()

KeyError: 'innings'

In [ ]:
merged_data.groupby(['match_id','innings'])['final_score'].max().head(10)

match_id  innings
335982    1          222
          2           82
335983    1          240
          2          207
335984    1          129
          2          132
335985    1          165
          2          166
335986    1          110
          2          112
Name: final_score, dtype: int64

In [ ]:
merged_data[
    ['match_id',
     'innings',
     'ball',
     'current_score',
     'final_score']
].head(30)

    match_id  innings  ball  current_score  final_score
0    1370353        1   0.1              0          214
1    1370353        1   0.2              0          214
2    1370353        1   0.3              1          214
3    1370353        1   0.4              2          214
4    1370353        1   0.5              3          214
5    1370353        1   0.6              4          214
6    1370353        1   1.1              4          214
7    1370353        1   1.2              5          214
8    1370353        1   1.3              6          214
9    1370353        1   1.4              7          214
10   1370353        1   1.5              7          214
11   1370353        1   1.6              8          214
12   1370353        1   2.1             14          214
13   1370353        1   2.2             14          214
14   1370353        1   2.3             18          214
15   1370353        1   2.4             22          214
16   1370353        1   2.5             24          214
17   1370353        1   2.6             24          214
18   1370353        1   3.1             28          214
19   1370353        1   3.2             32          214
20   1370353        1   3.3             36          214
21   1370353        1   3.4             37          214
22   1370353        1   3.5             38          214
23   1370353        1   3.6             38          214
24   1370353        1   4.1             39          214
25   1370353        1   4.2             41          214
26   1370353        1   4.3             45          214
27   1370353        1   4.4             46          214
28   1370353        1   4.5             48          214
29   1370353        1   4.6             49          214

In [ ]:
projected_score_data.columns

Index(['batting_team', 'bowling_team', 'venue_x', 'current_score',
       'wickets_lost', 'overs_completed', 'current_run_rate', 'final_score'],
      dtype='object')

In [ ]:
projected_score_data.head(10)

,batting_team,bowling_team,venue_x,current_score,wickets_lost,overs_completed,current_run_rate,final_score
5,Gujarat Titans,Chennai Super Kings,"Narendra Modi Stadium, Ahmedabad",4,0,1.0,4.000000,214
11,Gujarat Titans,Chennai Super Kings,"Narendra Modi Stadium, Ahmedabad",8,0,2.0,4.000000,214
17,Gujarat Titans,Chennai Super Kings,"Narendra Modi Stadium, Ahmedabad",24,0,3.0,8.000000,214
23,Gujarat Titans,Chennai Super Kings,"Narendra Modi Stadium, Ahmedabad",38,0,4.0,9.500000,214
29,Gujarat Titans,Chennai Super Kings,"Narendra Modi Stadium, Ahmedabad",49,0,5.0,9.800000,214
35,Gujarat Titans,Chennai Super Kings,"Narendra Modi Stadium, Ahmedabad",62,0,6.0,10.333333,214
41,Gujarat Titans,Chennai Super Kings,"Narendra Modi Stadium, Ahmedabad",67,1,7.0,9.571429,214
47,Gujarat Titans,Chennai Super Kings,"Narendra Modi Stadium, Ahmedabad",72,1,8.0,9.000000,214
53,Gujarat Titans,Chennai Super Kings,"Narendra Modi Stadium, Ahmedabad",80,1,9.0,8.888889,214
59,Gujarat Titans,Chennai Super Kings,"Narendra Modi Stadium, Ahmedabad",86,1,10.0,8.600000,214

In [ ]:
projected_score_data.shape

(38267, 8)

In [ ]:
merged_data[merged_data['innings'] == 1]['match_id'].nunique()

1005

In [ ]:
projected_score_data.shape[0] / 20

1913.35

In [ ]:
projected_score_data['overs_completed'].value_counts().sort_index()

overs_completed
1.000000     2010
2.000000     1541
2.166667      387
2.333333       65
2.500000       17
             ...
21.666667      16
21.833333       6
22.000000       2
22.166667       2
22.333333       3
Name: count, Length: 121, dtype: int64